# Generated by Django 5.0.7 on 2024-07-22 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daftar_Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(max_length=10)),
                ('nama_kelas', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Daftar Kelas',
            },
        ),
        migrations.CreateModel(
            name='Daftar_Pelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggaran', models.CharField(max_length=50)),
                ('poin_pelanggaran', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Daftar Pelanggaran',
            },
        ),
        migrations.CreateModel(
            name='Daftar_Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prestasi', models.CharField(max_length=50)),
                ('poin_prestasi', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Daftar Prestasi',
            },
        ),
        migrations.CreateModel(
            name='Daftar_Wali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('nama_wali', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Wali Kelas',
            },
        ),
        migrations.CreateModel(
            name='Daftar_Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.CharField(max_length=20, unique=True)),
                ('nama_siswa', models.CharField(max_length=50)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.daftar_kelas')),
            ],
            options={
                'verbose_name_plural': 'Daftar Siswa',
            },
        ),
        migrations.AddField(
            model_name='daftar_kelas',
            name='wali_kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.daftar_wali'),
        ),
    ]
