# Generated by Django 5.0.7 on 2024-07-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daftar_kelas',
            old_name='wali_kelas',
            new_name='wali_kelas_id',
        ),
    ]
