# Generated by Django 5.0.7 on 2024-07-22 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_rename_wali_kelas_daftar_kelas_wali_kelas_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daftar_kelas',
            old_name='wali_kelas_id',
            new_name='wali_kelas',
        ),
    ]
