# Generated by Django 5.0.7 on 2024-07-22 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_rename_wali_kelas_id_daftar_kelas_wali_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftar_siswa',
            name='wali_kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.daftar_wali'),
        ),
    ]
