# Generated by Django 5.0.7 on 2024-07-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poin_Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn_prestasi', models.CharField(max_length=20)),
                ('kategori_kelas', models.CharField(max_length=10)),
                ('nama_kelas', models.CharField(max_length=10)),
                ('prestasi', models.CharField(max_length=50)),
                ('catatan_prestasi', models.TextField()),
                ('poin_siswa_pres', models.IntegerField()),
                ('waktu_prestasi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Poin Prestasi',
            },
        ),
    ]
