# Generated by Django 5.0.7 on 2024-08-07 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_daftar_wali_user'),
        ('walikelas', '0004_alter_poin_prestasi_prestasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poin_prestasi',
            name='prestasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestasi_wali', to='administrator.daftar_prestasi'),
        ),
    ]
