# Generated by Django 5.0.7 on 2024-08-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walikelas', '0005_alter_poin_prestasi_prestasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poin_prestasi',
            name='poin_siswa_pres',
        ),
    ]
