# Generated by Django 5.0.7 on 2024-07-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poin_Pelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn_pelanggaran', models.CharField(max_length=20)),
                ('kategori_kelas', models.CharField(max_length=10)),
                ('nama_kelas', models.CharField(max_length=10)),
                ('pelanggaran', models.CharField(max_length=50)),
                ('poin_siswa_pel', models.IntegerField()),
                ('catatan_pelanggaran', models.TextField()),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Poin Pelanggaran',
            },
        ),
    ]
