# Generated by Django 5.0.7 on 2024-07-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_daftar_wali_user'),
        ('gurubk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poin_pelanggaran',
            name='kategori_kelas',
        ),
        migrations.RemoveField(
            model_name='poin_pelanggaran',
            name='nama_kelas',
        ),
        migrations.RemoveField(
            model_name='poin_pelanggaran',
            name='nisn_pelanggaran',
        ),
        migrations.AddField(
            model_name='poin_pelanggaran',
            name='siswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.daftar_siswa'),
        ),
        migrations.AddField(
            model_name='poin_pelanggaran',
            name='wali_kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.daftar_wali'),
        ),
    ]
