# Generated by Django 5.0.7 on 2024-08-07 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_daftar_wali_user'),
        ('gurubk', '0005_poin_pelanggaran_kategori_kelas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poin_pelanggaran',
            name='poin_siswa_pel',
        ),
        migrations.AlterField(
            model_name='poin_pelanggaran',
            name='pelanggaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pelanggaran_bk', to='administrator.daftar_pelanggaran'),
        ),
    ]
